version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: detection_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://admin:password@postgres:5432/detection_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
      - ./ml:/app/ml
      - ./datasets:/app/datasets
    depends_on:
      - postgres
      - redis

  worker:
    build: ./backend
    command: celery -A celery_worker worker --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://admin:password@postgres:5432/detection_db
      - REDIS_URL=redis://redis:6379
      - MODELS_DIR=/app/ml/weights
      - DATASETS_DIR=/app/datasets
    volumes:
      - ./uploads:/app/uploads
      - ./ml:/app/ml
      - ./datasets:/app/datasets
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
